---
services:
  exporter:
    build:
      context: .
      target: dev

  minio-init-bucket:
    image: docker.io/minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 minioadmin minioadmin;
        mc mb -p local/my-bucket;
        mc policy set public local/my-bucket;
        exit 0;
      "

  minio-init-content:
    image: minio/mc:latest
    depends_on:
      - minio
      - minio-init-bucket
    volumes:
      - ./test/assets:/data-to-upload:ro
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set local http://minio:9000 minioadmin minioadmin;
        mc cp --recursive /data-to-upload local/my-bucket/;
        exit 0;
      "
