[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log 
pidfile=/var/run/supervisord.pid
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:xinetd]
command=/sbin/xinetd -f /etc/xinetd.conf -stayalive -dontfork
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0
