[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log 
pidfile=/var/run/supervisord.pid
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:fcgiwrap]
command=spawn-fcgi -u default -g default -M 0775 -F 10 -s /var/run/fcgiwrap/fcgiwrap.socket -U default -G default /usr/bin/fcgiwrap
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false

[program:nginx]
command=nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0
