access_log  /dev/stdout  main;
error_log  /dev/stderr  debug;

server {

    listen       9773;
    server_name  localhost;

    root /opt/bin;

    location = /health {
        gzip off;
        fastcgi_pass unix:/var/run/fcgiwrap/fcgiwrap.socket;
        include /etc/nginx/fastcgi_params;
        fastcgi_param DOCUMENT_ROOT /opt/bin;
        fastcgi_param SCRIPT_FILENAME /opt/bin/health-http-wrapper;
    }

    location = /metrics {
        gzip off;
        fastcgi_pass unix:/var/run/fcgiwrap/fcgiwrap.socket;
        include /etc/nginx/fastcgi_params;
        fastcgi_param DOCUMENT_ROOT /opt/bin;
        fastcgi_param SCRIPT_FILENAME /opt/bin/metrics-http-wrapper;
    }


}